language: cpp
compiler:
    - gcc
dist: bionic
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - python3-setuptools

before_install:
    - pip3 install -U setuptools
    - pip3 install -U online-judge-tools=='9.*'
script:
    - bash test.sh
